# 数据源
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.66:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver

# MapperScan
mybatis-plus:
  # sql映射文件位置
  mapper-locations: classpath:/mapper/**/*.xml
  # 全局配置-主键自增
  global-config:
    db-config:
      id-type: auto